python manage.py create_users -user lferrer -pass l.ferrer
python manage.py create_users -user mgauder -pass m.gauder
python manage.py create_users -user cbonomi -pass c.bonomi
python manage.py create_users -user gbarchi -pass g.barchi
python manage.py create_users -user marcos -pass marcos
python manage.py create_users -user mari -pass mari
python manage.py create_users -user mmeza -pass m.meza
python manage.py create_users -user lestienne -pass l.estienne
python manage.py create_users -user user1 -pass user.1
python manage.py create_users -user user2 -pass user.2
python manage.py create_users -user user3 -pass user.3
python manage.py create_users -user user4 -pass user.4
python manage.py create_users -user user5 -pass user.5
python manage.py create_users -user user6 -pass user.6
python manage.py create_users -user user7 -pass user.7
python manage.py create_users -user user8 -pass user.8
python manage.py create_users -user user9 -pass user.9
python manage.py create_users -user user10 -pass user.10
python manage.py create_users -user user11 -pass user.11
python manage.py create_users -user user12 -pass user.12
python manage.py create_users -user user13 -pass user.13
python manage.py create_users -user user14 -pass user.14
python manage.py create_users -user user15 -pass user.15
python manage.py create_users -user user16 -pass user.16
python manage.py create_users -user user17 -pass user.17
python manage.py create_users -user user18 -pass user.18
python manage.py create_users -user user19 -pass user.19
python manage.py create_users -user user20 -pass user.20
python manage.py create_users -user user21 -pass user.21

python manage.py create_users -user user22 -pass user.22
python manage.py create_users -user user23 -pass user.23
python manage.py create_users -user user24 -pass user.24
python manage.py create_users -user user25 -pass user.25
python manage.py create_users -user user26 -pass user.26
python manage.py create_users -user user27 -pass user.27
python manage.py create_users -user user28 -pass user.28
python manage.py create_users -user user29 -pass user.29
python manage.py create_users -user user30 -pass user.30
python manage.py create_users -user user31 -pass user.31
python manage.py create_users -user user32 -pass user.32
python manage.py create_users -user user33 -pass user.33
python manage.py create_users -user user34 -pass user.34
python manage.py create_users -user user35 -pass user.35