# Generated by Django 4.0.4 on 2023-06-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(upload_to='audios/')),
                ('name', models.CharField(max_length=255)),
                ('speaker_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dim_O', models.CharField(blank=True, choices=[('A', 'A'), ('No se', 'No se'), ('B', 'B')], max_length=20, null=True)),
                ('dim_C', models.CharField(blank=True, choices=[('A', 'A'), ('No se', 'No se'), ('B', 'B')], max_length=20, null=True)),
                ('dim_E', models.CharField(blank=True, choices=[('A', 'A'), ('No se', 'No se'), ('B', 'B')], max_length=20, null=True)),
                ('dim_A', models.CharField(blank=True, choices=[('A', 'A'), ('No se', 'No se'), ('B', 'B')], max_length=20, null=True)),
                ('dim_N', models.CharField(blank=True, choices=[('A', 'A'), ('No se', 'No se'), ('B', 'B')], max_length=20, null=True)),
                ('submit', models.BooleanField(default=False)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('audio_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='A', to='pair_comparison.audio')),
                ('audio_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B', to='pair_comparison.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
