# Generated by Django 4.0.4 on 2023-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_comparison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='dim_A',
            field=models.CharField(blank=True, choices=[('Izquierda', 'Izquierda'), ('Derecha', 'Derecha')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_C',
            field=models.CharField(blank=True, choices=[('Izquierda', 'Izquierda'), ('Derecha', 'Derecha')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_E',
            field=models.CharField(blank=True, choices=[('Izquierda', 'Izquierda'), ('Derecha', 'Derecha')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_N',
            field=models.CharField(blank=True, choices=[('Izquierda', 'Izquierda'), ('Derecha', 'Derecha')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_O',
            field=models.CharField(blank=True, choices=[('Izquierda', 'Izquierda'), ('Derecha', 'Derecha')], max_length=20, null=True),
        ),
    ]
