# Generated by Django 4.0.4 on 2023-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_comparison', '0002_alter_annotation_dim_a_alter_annotation_dim_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='dim_A',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_C',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_E',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_N',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dim_O',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=20, null=True),
        ),
    ]
